Feature/layout
CyberSecurityLabPL/elektronik-app pull request #11
Opened 2024-11-12 10:41 UTC by Pullolo

Welcome pages, Layout, Async Storage, Input, Select, Button Component, SVGs

2024-11-12 11:35 UTC, wybran requested changes

2024-11-12 11:35 UTC, wybran commented on src/app/(drawer)/(settings)/notifications.tsx
> +		const backAction = () => {
funkcje sie nie wykonają

2024-11-12 11:35 UTC, wybran commented on src/app/(drawer)/(settings)/profile.tsx
> +			router.navigate("/(drawer)/(tabs)/home")
to samo

2024-11-12 11:35 UTC, wybran commented on src/app/(drawer)/(tabs)/home.tsx
> +				}}
tymczasowe

2024-11-12 11:35 UTC, wybran commented on src/app/(drawer)/(tabs)/radio.tsx
> +			{/* @ts-expect-error */}
😿

2024-11-12 11:35 UTC, wybran commented on src/app/(welcome)/set-up.tsx
> +	const [name, setName] = useState("")
użyć do formularzy react hook form

2024-11-12 14:18 UTC, wybran requested changes

2024-11-12 14:18 UTC, wybran commented on src/app/(welcome)/set-up.tsx
> +  } = useForm({
https://legacy.react-hook-form.com/ts/

example:
type FormValues = {
  firstName: string;
  lastName: string;
};
  const { register, handleSubmit, formState: { errors } } = useForm<FormValues>();

2024-11-12 14:18 UTC, wybran commented on src/app/index.tsx
> +const page = () => {
to zmałej?

2024-11-12 14:18 UTC, wybran commented on src/components/navigation/Sidebar.tsx
> +const Sidebar = (props: any) => {
any?
😞

2024-11-13 07:33 UTC, Carpye commented
Formatowanie będzie po mergu jak już nie będzie zmian.
Generalnie tab size defaultowy na gh to 8, dlatego wszystko takie ogromne jest, jak się zmieni na 2 w preferencjach to jest normalnie, ale zmienimy i tak na spacje żeby u każdego było tak samo.

2024-11-13 07:37 UTC, Carpye commented on src/app/(welcome)/set-up.tsx
> +  } = useForm({
nie wiedzielismy dokaldnie o co chodzi ale cos tam zmienione krzysiu mowi

2024-11-13 08:24 UTC, wybran approved these changes

2024-11-13 08:24 UTC, merged